swagger: "2.0"
info:
  version: "0.0.1"
  title: HTM Auth endpoint
# during dev, should point to your local machine
host: localhost:8081
# basePath prefixes all resource paths
basePath: "/api"
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - text/plain
# format of the responses to the client (Accepts)
produces:
  - application/json
  - text/plain
paths:
  /auth:
    # binds a127 app logic to a route
    x-swagger-router-controller: authentication_controller
    post:
      description: Allows authentication on our site
      operationId: authentication
      parameters:
        - name: username
          in: body
          description: Username and Password to create a session
          required: true
          schema:
            $ref: "#/definitions/Request"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Request"
  /device:
    # binds a127 app logic to a route
    x-swagger-router-controller: devices_controller
    post:
      description: Allows authentication on our site
      operationId: createDevice
      parameters:
        - name: device
          in: body
          description: Device details to create a new device
          required: true
          schema:
            $ref: "#/definitions/DeviceRequest"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DeviceRequest"
  /validate-device:
    # binds a127 app logic to a route
    x-swagger-router-controller: devices_controller
    post:
      description: Allows authentication on our site
      operationId: enableDevice
      parameters:
        - name: device
          in: body
          description: Device details to create a new device
          required: true
          schema:
            $ref: "#/definitions/DeviceRequest"
      responses:
        "200":
          description: Success
  /devices:
    # binds a127 app logic to a route
    x-swagger-router-controller: devices_controller
    get:
      description: Allows a authenticated user to get devices
      operationId: findDevices
      parameters:
        - name: device
          in: body
          description: Return all devices in our system
          required: true
          schema:
            $ref: "#/definitions/QueryDeviceRequest"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/QueryDeviceRequest"
  /user:
    x-swagger-router-controller: users_controller
    post:
      description: Creates a new user if valid
      operationId: createUser
      parameters:
        - name: username
          in: query
          description: The username of the user
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Request"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Request:
    properties:
      username:
        type: string
      password:
        type: string
  DeviceRequest:
    properties:
      name:
        type: string
      description:
        type: string
      status:
        type: string
  QueryDeviceRequest:
    properties:
      deviceId:
        type: string
      name:
        type: string
      description:
        type: string
      status:
        type: string
