swagger: "2.0"
info:
  version: "0.0.1"
  title: HTM Auth endpoint
# during dev, should point to your local machine
host: localhost
# basePath prefixes all resource paths
basePath: "/api"
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /auth:
    # binds a127 app logic to a route
    x-swagger-router-controller: authentication_controller
    post:
      description: Allows authentication on our site
      operationId: authentication
      parameters:
        - name: "body"
          in: "body"
          description: The username of the user
          required: true
          schema:
            $ref: "#/definitions/Request"          
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Request"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Request:
    properties:
      username:
        type: string
